DELETE FROM Classes; INSERT INTO Classes(classID, className, subject, credit, quarters, instructor) VALUES 
('ENVS 23', 'ENVS 23 The Physical and Chemical Environment', 'Environmental Studies', '5', 'Spring', 'Michael Loik'),
('CHEM 1A', 'CHEM 1A General Chemistry', 'Chemistry and Biochemistry', '5', 'Fall, Winter, Spring, Summer', 'Alegra Eroy-Reveles, Seth Rubin'),
('ENVS 24', 'ENVS 24 General Ecology', 'Environmental Studies', '5', 'Fall', 'Kai Zhu'),
('BIOE 20C', 'BIOE 20C Ecology and Evolution', 'Biology: Ecology and Evolutionary', '5', 'Fall, Winter, Spring, Summer', 'Baldo Marinovic'),
('STAT 7', 'STAT 7 Statistical Methods for the Biological, Environmental, and Health Sciences', 'Statistics', '5', 'Fall, Winter, Spring, Summer', 'The Staff, Herbert Lee, Raquel Prado, Bruno Mendes, David Draper, Claudia Wehrhahn-Cortes, Ju Hee Lee, Zehang "Richard" Li'),
('STAT 7L', 'STAT 7L Statistical Methods for the Biological, Environmental, and Health Sciences Laboratory', 'Statistics', '2', 'Fall, Winter, Spring, Summer', 'The Staff, Herbert Lee, Raquel Prado, David Draper, Claudia Wehrhahn-Cortes, Ju Hee Lee, Zehang "Richard" Li'),
('ENVS 25', 'ENVS 25 Environmental Policy and Economics', 'Environmental Studies', '5', 'Winter, Summer', 'Sikina Jinnah'),
('ENVS 80F', 'ENVS 80F Introduction to Agroecology and Sustainable Food Systems', 'Environmental Studies', '5', 'Fall', 'Damian Parr'),
('AM 3', 'AM 3 Precalculus for the Social Sciences', 'Applied Mathematics', '5', 'Winter', 'Marcella Gomez, Bruno Mendes, Pascale Garaud'),
('AM 6', 'AM 6 Precalculus for Statistics', 'Applied Mathematics', '5', '', 'The Staff, Bruno Mendes'),
('MATH 3', 'MATH 3 Precalculus', 'Mathematics', '5', 'Fall, Winter, Spring, Summer', ''),
('ANTH 2', 'ANTH 2 Introduction to Cultural Anthropology', 'Anthropology', '5', 'Winter, Summer', 'Melissa Caldwell'),
('BME 80G', 'BME 80G Bioethics in the 21st Century: Science, Business, and Society', 'Biomolecular Engineering', '5', 'Fall', 'The Staff'),
('PHIL 22', 'PHIL 22 Introduction to Ethical Theory', 'Philosophy', '5', 'Winter', 'Janette Dinishak'),
('PHIL 24', 'PHIL 24 Introduction to Ethics: Contemporary Moral Issues', 'Philosophy', '5', '', ''),
('PHIL 28', 'PHIL 28 Environmental Ethics', 'Philosophy', '5', '', ''),
('SOCY 1', 'SOCY 1 Introduction to Sociology', 'Sociology', '5', 'Fall, Spring, Summer', 'Christie McCullen, Megan McNamera'),
('SOCY 10', 'SOCY 10 Issues and Problems in American Society', 'Sociology', '5', 'Winter, Summer', 'Jenny Reardon'),
('SOCY 15', 'SOCY 15 World Society', 'Sociology', '5', 'Fall, Summer', 'Steven McKay'),
('ENVS 100', 'ENVS 100 Ecology and Society', 'Environmental Studies', '3', 'Winter, Spring', 'Gregory Gilbert, Madeleine Fairbairn'),
('ENVS 100L', 'ENVS 100L Ecology and Society Writing Laboratory', 'Environmental Studies', '5', 'Winter, Spring', 'Gregory Gilbert, Madeleine Fairbairn, Murai Emily'),
('ENVS 130A', 'ENVS 130A Agroecology and Sustainable Agriculture', 'Environmental Studies', '5', 'Fall', 'Katie Monsen'),
('ENVS 130L', 'ENVS 130L Agroecology and Sustainable Agriculture Laboratory', 'Environmental Studies', '2', 'Fall', 'Katie Monsen'),
('ENVS 130B', 'ENVS 130B Justice and Sustainability in Agriculture', 'Environmental Studies', '5', 'Winter', 'Maywa Montenegro'),
('ENVS 130C', 'ENVS 130C Field Experiences in Agroecology and Sustainable Food', 'Environmental Studies', '5', 'Spring', 'Stacy The Staff'),
('ENVS 133', 'ENVS 133 Agroecology Practicum', 'Environmental Studies', '5', 'Winter, Spring', 'Katie Monsen, Damian Parr'),
('ENVS 135', 'ENVS 135 Sustainable Aquaculture', 'Environmental Studies', '5', 'Winter', 'Pallab Sarker'),
('ENVS 108', 'ENVS 108 General Entomology', 'Environmental Studies', '5', 'Fall', 'Andy Kulikowski'),
('ENVS 108L', 'ENVS 108L General Entomology Laboratory', 'Environmental Studies', '3', '', ''),
('ENVS 129', 'ENVS 129 Integrated Pest Management', 'Environmental Studies', '5', '', ''),
('ENVS 131', 'ENVS 131 Insect Ecology', 'Environmental Studies', '5', '', ''),
('ENVS 142', 'ENVS 142 Sustainable Energy', 'Environmental Studies', '5', 'Winter', 'Elliott Campbell'),
('ENVS 143', 'ENVS 143 Sustainable Development: Economy, Policy, and Environment', 'Environmental Studies', '5', 'Fall', 'Jeffrey Bury'),
('ENVS 146', 'ENVS 146 Water Quality: Policy, Regulation, and Management', 'Environmental Studies', '5', '', 'Daniel Press'),
('ENVS 160', 'ENVS 160 Restoration Ecology', 'Environmental Studies', '5', 'Winter', 'Karen Holl'),
('ENVS 161A', 'ENVS 161A Soils and Plant Nutrition', 'Environmental Studies', '5', 'Winter', 'Weixin Cheng'),
('ENVS 162', 'ENVS 162 Plant Physiological Ecology', 'Environmental Studies', '5', 'Winter', 'Michael Loik'),
('ENVS 162L', 'ENVS 162L Plant Physiological Ecology Laboratory', 'Environmental Studies', '2', 'Winter', 'Michael Loik'),
('ENVS 163', 'ENVS 163 Plant Disease Ecology', 'Environmental Studies', '5', 'Fall', 'Gregory Gilbert'),
('ENVS 163L', 'ENVS 163L Plant Disease Ecology Lab', 'Environmental Studies', '2', 'Fall', 'Gregory Gilbert'),
('ENVS 164', 'ENVS 164 Projects and Practices in Soil Ecology', 'Environmental Studies', '5', 'Spring', 'Weixin Cheng'),
('ENVS 165', 'ENVS 165 Sustainable Water Systems', 'Environmental Studies', '5', 'Fall', 'Brent Haddad'),
('ENVS 166', 'ENVS 166 Agroecosystem Analysis and Watershed Management', 'Environmental Studies', '5', '', ''),
('ENVS 168', 'ENVS 168 Biogeochemistry and the Global Environment', 'Environmental Studies', '5', '', ''),
('ENVS 169', 'ENVS 169 Climate Change Ecology', 'Environmental Studies', '5', 'Fall', 'Michael Loik'),
('ENVS 170', 'ENVS 170 Agriculture and Climate Change', 'Environmental Studies', '5', 'Winter', 'Katie Monsen'),
('BIOE 118', 'BIOE 118 Plants and Society: the Biology of Food, Shelter, and Medicine', 'Biology: Ecology and Evolutionary', '5', 'Spring', 'The Staff'),
('CMMU 149', 'CMMU 149 Political Economy of Food and Agriculture', 'Community Studies', '5', '', 'Julie Guthman'),
('CMMU 186', 'CMMU 186 Food and Agriculture Social Movements', 'Community Studies', '5', 'Fall, Winter', ''),
('ENVS 83', 'ENVS 83 Environmental Studies Internship', 'Environmental Studies', '5', 'Fall, Winter, Spring', ''),
('ENVS 184', 'ENVS 184 Environmental Studies Internship', 'Environmental Studies', '2', 'Fall, Winter, Spring', ''),
('ENVS 199F', 'ENVS 199F Tutorial', 'Environmental Studies', '2', 'Fall, Winter, Spring', ''),
('ENVS 190', 'ENVS 190 Capstone Course: Environmental Problem Solving', 'Environmental Studies', '5', 'Spring', 'Katie Monsen'),
('ENVS 195B', 'ENVS 195B Senior Thesis Group', 'Environmental Studies', '5', 'Fall, Winter, Spring', ''),
('ENVS 196', 'ENVS 196 Senior Seminar', 'Environmental Studies', '5', 'Fall, Winter, Spring', 'Karen Holl, Michael Loik, Carol Shennan, Barry Nickel'),
('ENVS 183A', 'ENVS 183A Senior Internship', 'Environmental Studies', '5', 'Fall, Winter, Spring', ''),
('ENVS 183B', 'ENVS 183B Senior Internship', 'Environmental Studies', '5', 'Fall, Winter, Spring', ''),
('ENVS 195A', 'ENVS 195A Senior Research', 'Environmental Studies', '5', 'Fall, Winter, Spring', '');
DELETE FROM Requirements; INSERT INTO Requirements(classID, preReq, gradReq) VALUES 
('ENVS 23', '', 'Agroecology B.A.'),
('CHEM 1A', 'Previous or concurrent enrollment in MATH 3, AM 3, or equivalent, or a mathematics placement score of 300 or higher; taking the online chemistry self-assessment exam is strongly recommended.', 'Agroecology B.A.'),
('ENVS 24', 'AM 3 or AM 6, or MATH 3 or higher; or mathematics placement examination (MPE) score of 300 or higher; or AP Calculus AB exam score of 3 or higher; ENVS 23 recommended as prerequisite to this course.', 'Agroecology B.A.'),
('BIOE 20C', '', 'Agroecology B.A.'),
('STAT 7', 'score of 300 or higher on the mathematics placement examination (MPE), or AM 3 or AM 6 or AM 11A or AM 15A or MATH 3 or MATH 11A or MATH 19A. Concurrent enrollment in STAT 7L is required.', 'Agroecology B.A.'),
('STAT 7L', 'score of 300 or higher on the mathematics placement examination (MPE), AM 3 or AM 6 or AM 11A or AM 15A or MATH 3 or MATH 11A or MATH 19A. Concurrent enrollment in STAT 7 is required.', 'Agroecology B.A.'),
('ENVS 25', '', 'Agroecology B.A.'),
('ENVS 80F', '', 'Agroecology B.A.'),
('AM 3', 'score of 200 or higher on the mathematics placement examination (MPE), or MATH 2.', 'Agroecology B.A.'),
('AM 6', 'MATH 2 or mathematics placement examination (MPE) score of 200 or higher or higher.', 'Agroecology B.A.'),
('MATH 3', 'MATH 2 or mathematics placement (MP) score of 200 or higher. Students may not enroll in or receive credit for MATH 3 after receiving credit with a "C" or better in AM 11A, MATH 11A, MATH 19A, MATH 20A or equivalents.', 'Agroecology B.A.'),
('ANTH 2', '', 'Agroecology B.A.'),
('BME 80G', '', 'Agroecology B.A.'),
('PHIL 22', '', 'Agroecology B.A.'),
('PHIL 24', '', 'Agroecology B.A.'),
('PHIL 28', '', 'Agroecology B.A.'),
('SOCY 1', '', 'Agroecology B.A.'),
('SOCY 10', '', 'Agroecology B.A.'),
('SOCY 15', '', 'Agroecology B.A.'),
('ENVS 100', 'ENVS 23 or CHEM 1A; ENVS 24 or BIOE 20C; ENVS 25; and STAT 7 and STAT 7L, or ECON 113 or OCEA 90; and one from: ANTH 2, SOCY 1, SOCY 10, SOCY 15, PHIL 21, PHIL 22, PHIL 24, PHIL 28, or PHIL 80G. Concurrent enrollment in ENVS 100L Is required.', 'Agroecology B.A.'),
('ENVS 100L', 'Satisfaction of the Entry Level Writing and Composition requirements. Concurrent enrollment in ENVS 100 is required.', 'Agroecology B.A.'),
('ENVS 130A', 'Concurrent enrollment in ENVS 130L and previous or concurrent enrollment in ENVS 100 and ENVS 100L, or by permission of instructor.', 'Agroecology B.A.'),
('ENVS 130L', '', 'Agroecology B.A.'),
('ENVS 130B', 'Previous or concurrent enrollment in ENVS 100 and ENVS 100L, or by permission of instructor.', 'Agroecology B.A.'),
('ENVS 130C', 'previous or concurrent enrollment in ENVS 100 and ENVS 100L.', 'Agroecology B.A.'),
('ENVS 133', 'Previous or concurrent enrollment in ENVS 100 and ENVS 100L, or by permission of instructor.', 'Agroecology B.A.'),
('ENVS 135', 'Previous or concurrent enrollment in ENVS 100 and ENVS 100L.', 'Agroecology B.A.'),
('ENVS 108', 'Previous or concurrent enrollment in ENVS 100 and ENVS 100L required, or by permission of instructor.', 'Agroecology B.A.'),
('ENVS 108L', '', 'Agroecology B.A.'),
('ENVS 129', 'Previous or concurrent enrollment in ENVS 100 and ENVS 100L, or by permission of instructor.', 'Agroecology B.A.'),
('ENVS 131', 'previous or concurrent enrollment in ENVS 100 and ENVS 100L, or by permission of instructor.', 'Agroecology B.A.'),
('ENVS 142', 'Previous or concurrent enrollment in ENVS 100 and ENVS 100L, or by permission of instructor.', 'Agroecology B.A.'),
('ENVS 143', 'Previous or concurrent enrollment in ENVS 100 and ENVS 100L, or by permission of instructor.', 'Agroecology B.A.'),
('ENVS 146', 'ENVS 100 and ENVS 100L; and ENVS 140, ENVS 149, ENVS 150 or ENVS 165.', 'Agroecology B.A.'),
('ENVS 160', 'Previous or concurrent enrollment in ENVS 100 and ENVS 100L, or by permission of instructor.', 'Agroecology B.A.'),
('ENVS 161A', 'Previous or concurrent enrollment in ENVS 100 and ENVS 100L, or by permission of instructor.', 'Agroecology B.A.'),
('ENVS 162', 'Previous or concurrent enrollment in ENVS 100 and ENVS 100L, or by permission of instructor.', 'Agroecology B.A.'),
('ENVS 162L', 'Previous or concurrent enrollment in ENVS 100 and ENVS 100L, or by permission of instructor.', 'Agroecology B.A.'),
('ENVS 163', 'Previous or concurrent enrollment in ENVS 100 and ENVS 100L, or by permission of instructor.', 'Agroecology B.A.'),
('ENVS 163L', 'concurrent enrollment in ENVS 163 is required.', 'Agroecology B.A.'),
('ENVS 164', 'Previous or concurrent enrollment in ENVS 100 and ENVS 100L, or by permission of the instructor. Previous enrollment in ENVS 161 is recommended.', 'Agroecology B.A.'),
('ENVS 165', 'Previous or concurrent enrollment in ENVS 100 and ENVS 100L, or by permission of instructor.', 'Agroecology B.A.'),
('ENVS 168', 'Previous or concurrent enrollment in ENVS 100 and ENVS 100L required, or by permission of instructor.', 'Agroecology B.A.'),
('ENVS 169', 'Previous or concurrent enrollment in ENVS 100 and ENVS 100L required, or by permission of instructor.', 'Agroecology B.A.'),
('ENVS 170', 'previous or concurrent enrollment in ENVS 100 and ENVS 100L.', 'Agroecology B.A.'),
('BIOE 118', 'BIOL 20A and BIOE 20B and BIOE 20C; or ENVS 23 and ENVS 24.', 'Agroecology B.A.'),
('CMMU 149', '', 'Agroecology B.A.'),
('CMMU 186', '', 'Agroecology B.A.'),
('ENVS 83', '', 'Agroecology B.A.'),
('ENVS 184', '', 'Agroecology B.A.'),
('ENVS 199F', '', 'Agroecology B.A.'),
('ENVS 190', 'ENVS 100 and ENVS 100L; Entry Level Writing and Composition requirements. Enrollment is restricted to senior environmental studies majors and the combined majors with Earth sciences, biology, and economics.', 'Agroecology B.A.'),
('ENVS 195B', 'Completion of ENVS 100 and ENVS 100L and ENVS 195A.', 'Agroecology B.A.'),
('ENVS 196', 'Entry Level Writing and Composition requirements.', 'Agroecology B.A.'),
('ENVS 183A', '', 'Agroecology B.A.'),
('ENVS 183B', 'ENVS 183A. Students submit petition to course-sponsoring agency. Enrollment is restricted to environmental studies majors and the combined majors with Earth sciences, biology, and economics.', 'Agroecology B.A.'),
('ENVS 195A', 'Completion of ENVS 100 and ENVS 100L, and Entry Level Writing and Composition requirements.', 'Agroecology B.A.');
